# Week 08: Local/Global Variables

## 0. Import Libraries 

In [2]:
# the "pandas" library is for manipualting datasets
import pandas as pd
import numpy as np
np.random.seed(100)

## 1. Array Continued (Stacking)

<font size='4'>

In [3]:
# 9.1.
x = np.ones((4,))
print(x)
print()
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Concatentate `my_array` and `x`
print(np.concatenate([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=1))

[1. 1. 1. 1.]

[1. 2. 3. 4. 1. 1. 1. 1.]

[[1. 2. 3. 4.]
 [1. 1. 1. 1.]]

[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]


In [12]:
# 9.2. Stack arrays row-wise (by Python's default)
print(my_array)
print()
print(my_2d_array)
print()
print(np.vstack([my_array,my_2d_array]))
print()

print()

print(my_resized_array)
print()
print(np.hstack([my_resized_array,my_2d_array]))

[1 2 3 4]

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]


[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [18]:
# 9.3.
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
print("my_resized_array", my_resized_array)

my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)
print("my_2d_array", my_2d_array)

my_stacked_array = np.hstack([my_resized_array,my_2d_array])
print("my_stacked_array",my_stacked_array)
print()
# if the second argument is an integer, it will split the array into an N equal sub-arrays
# Split `my_stacked_array` horizontally into two equal sub-arrays
print(np.split(my_stacked_array,2))
# Split `my_stacked_array` vertically into two equal sub-arrays
print(np.split(my_stacked_array, 2, axis=0))

my_resized_array [[1 2 3 4]
 [1 2 3 4]]
my_2d_array [[1 2 3 4]
 [5 6 7 8]]
my_stacked_array [[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]

[array([[1, 2, 3, 4, 1, 2, 3, 4]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]
[array([[1, 2, 3, 4, 1, 2, 3, 4]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]


In [19]:
# 9.4. Use indices in the form of a numpy array
print(my_stacked_array)
print(np.split(my_stacked_array,np.array([2,5]),axis=1))
print("or")
print(np.hsplit(my_stacked_array,np.array([2,5])))

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]
[array([[1, 2],
       [1, 2]]), array([[3, 4, 1],
       [3, 4, 5]]), array([[2, 3, 4],
       [6, 7, 8]])]
or
[array([[1, 2],
       [1, 2]]), array([[3, 4, 1],
       [3, 4, 5]]), array([[2, 3, 4],
       [6, 7, 8]])]


In [21]:
# 9.5. Let's create a practical example and call back from the blood pressue problem.
# (2, 10, 5) refers to two sites, 10 patients each site, and 5 time points per patient.
BP_3d_arr = np.random.uniform(low=70, high=100, size=(2, 10, 5))
print(BP_3d_arr)
print(BP_3d_arr.shape)

[[[93.34867646 93.38795196 88.3098446  79.27001046 90.93204723]
  [95.78854887 88.75971273 99.47223489 99.29500381 75.00082394]
  [70.69534409 74.82233646 97.70490476 98.6064955  76.32935256]
  [80.81575752 86.48125785 78.15492548 83.81804863 90.88484694]
  [85.0106769  91.48212972 85.77867809 70.04197069 81.8410086 ]
  [84.7650091  82.08640994 80.628949   85.01842958 83.35529886]
  [72.71298365 78.2068876  98.30431293 70.79633924 71.19996069]
  [78.49421079 87.47032511 99.72678409 99.77926712 99.79352117]
  [73.30144993 89.93444338 85.71960503 75.19449729 98.28880735]
  [77.25580258 99.96796807 87.48081445 75.49837002 81.60536266]]

 [[75.69020587 82.32312019 87.84040207 91.49758279 84.60674447]
  [79.28769453 87.32324118 83.25123459 80.79034308 79.63995796]
  [76.24621721 83.53775872 84.75528731 96.97228944 91.88081383]
  [93.10269319 81.26317743 80.31218606 89.65105618 91.3311398 ]
  [73.40612726 73.99086068 83.68117173 74.7920869  98.84925711]
  [95.12847235 85.60482061 76.54816773

In [24]:
# 9.5.1 axis takes one number
BP_3d_arr_mean_1 = np.mean(BP_3d_arr,axis=0)
print(BP_3d_arr_mean_1)
print(BP_3d_arr_mean_1.shape)
print()

BP_3d_arr_mean_2 = np.mean(BP_3d_arr,axis=1)
print(BP_3d_arr_mean_2)
print(BP_3d_arr_mean_2.shape)
print()

BP_3d_arr_mean_3 = np.mean(BP_3d_arr,axis=2)
print(BP_3d_arr_mean_3)
print(BP_3d_arr_mean_3.shape)
print()

BP_3d_arr_mean_3 = np.mean(BP_3d_arr,axis=-1)
print(BP_3d_arr_mean_3)
print(BP_3d_arr_mean_3.shape)

[[84.51944117 87.85553607 88.07512333 85.38379662 87.76939585]
 [87.5381217  88.04147696 91.36173474 90.04267344 77.32039095]
 [73.47078065 79.18004759 91.23009603 97.78939247 84.1050832 ]
 [86.95922536 83.87221764 79.23355577 86.73455241 91.10799337]
 [79.20840208 82.7364952  84.72992491 72.4170288  90.34513286]
 [89.94674072 83.84561528 78.58855837 79.53299563 91.36370461]
 [81.96214426 87.00307715 89.95974588 74.16067992 75.09155063]
 [87.10053832 85.82992241 94.81254775 96.97556267 88.69146816]
 [72.84432655 90.95863076 92.28076468 86.90431966 91.50188945]
 [83.11078226 95.97890933 92.27654978 75.18288879 81.89090116]]
(10, 5)

[[81.21884599 87.25994228 90.12810533 83.73184323 84.923103  ]
 [84.11325462 85.8004434  86.38161491 85.29293485 86.91439905]]
(2, 5)

[[89.04970614 91.66326485 83.63168667 84.03096729 82.8308928  83.1708193
  78.24409682 93.05282166 84.4877606  84.36166356]
 [84.39161108 82.05849427 86.6784733  87.13205053 80.94390074 86.14022655
  85.02678232 88.31119407 8

In [26]:
# 9.5.2 axis takes two numbers
BP_3d_arr_mean_4 = np.mean(BP_3d_arr,axis=(1,2))
print(BP_3d_arr_mean_4)
print(BP_3d_arr_mean_4.shape)
print()

BP_3d_arr_mean_5 = np.mean(BP_3d_arr,axis=(0,2))
print(BP_3d_arr_mean_5)
print(BP_3d_arr_mean_5.shape)
print()

[85.45236797 85.70052937]
(2,)

[86.72065861 86.86087956 85.15507999 85.58150891 81.88739677 84.65552292
 81.63543957 90.68200786 86.89798622 85.68800626]
(10,)



In [28]:
# 9.5.3. axis takes three numbers or None
BP_3d_arr_mean_7 = np.mean(BP_3d_arr,axis=(0,1,2))
print(BP_3d_arr_mean_7)
print(BP_3d_arr_mean_7.shape)
print("or")
BP_3d_arr_mean_7 = np.mean(BP_3d_arr,axis=None)
print(BP_3d_arr_mean_7)
print(BP_3d_arr_mean_7.shape)

85.57644866677343
()
or
85.57644866677343
()


## 2. Local and Global Variables

<font size="4"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook



<font size = "5">
Example:

In [9]:
message_hello = "hello"
number3       = 3

In [10]:
print(message_hello + " world")
print(number3 * 2)

hello world
6


<font size = "4">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "4">

$f(x,y,z) = x + y + z$

In [35]:
# 2.1. Correct Example:
def fn_add_recommended(x,y,z):
    return x+y+z

print(fn_add_recommended(x=1,y=2,z=5))
print(fn_add_recommended(1,2,5))

8
8


In [36]:
# 2.2. Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment
def fn_add_notrecommended(x,y):
    return x+y+z

z=5
print(fn_add_notrecommended(x=1,y=2))
print(fn_add_notrecommended(1,2))

8
8


In [11]:
# 2.2.1.
del z # remove variables from a global scope


NameError: name 'z' is not defined

<font size ="4">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables


### Local variables supercede global variables

In [37]:
# 2.3.
del x
def print_x():
    x=20
    print(x)

print_x()
print('outside')
print(x)

20
outside


NameError: name 'x' is not defined

In [38]:
# 2.4. An exception
depart_ls = ['bios','epid','bshes']
for id_iter, depart_iter in enumerate(depart_ls):
    print(id_iter,depart_iter)

print(id_iter,depart_iter)

0 bios
1 epid
2 bshes
2 bshes


In [39]:
# 2.5. This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function are "invisible"
# or "inaccessible" when exiting the function.

def fn_square(x):
    y = x**2
    return y

x=5
y=-5
print(fn_square(1.2))

print(x)
print(y)

1.44
5
-5


### Local variables are **not** stored in the working environment

In [47]:
# 2.6. The following code assigns a global variable x
x=5
y=44
print(fn_square(10))
print(x)
print(y)

x=6
y=4
print(fn_square(20))
print(x)
print(y)

100
5
44
400
6
4


### To permanently modify a variable, use the "global" command

In [48]:
# 2.7.
def modify_x():
    global x
    x = x+5

x=1
print("x={}before modification".format(x))
modify_x()
print("x={}after modification".format(x))

x=1before modification
x=6after modification


### Try it yourself:

<font size = "4">
    
- What happens if we run `modify_x` twice?
- What happens if we add `global y` inside `fn_square`?

In [62]:
# 2.8. Write your own code here
def modify_x():
    global x
    x = x+5

x=1
print("x={}before modification".format(x))
modify_x()
print("x={}after modification".format(x))
modify_x()
print("x={}after modification".format(x))
modify_x()
print("x={}after modification".format(x))


print()

def fn_square_2(x):
    global y 
    y = x**2
    return y
x=5
y=-5

print("before square")
print(x,y)
print("after square")
print(fn_square_2(x=1.2))
print(x)
print(y)


x=1before modification
x=6after modification
x=11after modification
x=16after modification

before square
5 -5
after square
1.44
5
1.44


In [63]:
# 2.9.
import builtins
print(dir(builtins))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'S

### Built-in scope (Variables defined in Python)

<font size='4'>

- Functions such as `print()`, `len()`, `sum()`, `isinstance()` are all built-in functions in Python.
- They are available in any part of your code, so no need to define them.
- Python has a list of variables that are always available to prevent you from using the same names.
- Most of them are error names.

In [64]:
# 2.10


### Enclosing scope (Variables defined in enclosing functions)

<font size='4'>
    
- They refer to variables defined in enclosing functions
- Enclosing functions are functions that contain other functions (nested or hierarachical functions)
- Enclosing scope is between local and global scopes in the LEGB rule

In [67]:
# 2.11
# Define a function that contains another function
def outer():
    x = 'outer -> x'

    def inner():
        x = 'inner -> x'
        print(x)
    inner()
    print(x)

In [68]:
outer()

inner -> x
outer -> x


## 3. Work with Python scripts

<font size='4'>

Please open `week_08_main_1.py` and `week_08_main_2.py`.